{
 "title": "Stafi: substrate metrics",
 "description": "Grafana dashboard for substrate node metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "stafi" },
   {
    "name": "nodeport",
    "label": "Host-Port:",
    "query": "label_values(substrate_block_height{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "stafi: block sync  rate ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(substrate_block_height{job=\"stafi\",status=\"best\"}[5m])",
     "legendFormat": "best-{{instance}}"
    },
    {
     "expr": "rate(substrate_block_height{job=\"stafi\",status=\"sync_target\"}[5m])",
     "legendFormat": "finalized-{{instance}}"
    },
    {
     "expr": "rate(substrate_block_height{job=\"stafi\",status=\"finalized\"}[5m])",
     "legendFormat": "sync_target-{{instance}}"
    }
   ]
  },
  {
   "title": "stafi: Number of network gossip peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{job=\"stafi\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "substrate_memory_usage_bytes{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Height of the chain",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "substrate_block_height{instance=~\"$nodeport\",job=~\"$job\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Networking bytes per second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "substrate_network_per_sec_bytes{instance=~\"$nodeport\",job=\"$job\"}",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "substrate_cpu_usage_percentage{job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of transactions in the ready queue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "substrate_ready_transactions_number{instance=~\"$nodeport\",job=~\"$job\"}",
     "legendFormat": "Number of transactions in the ready queue"
    }
   ]
  }
 ]
}